Repository spryker/jarvis, pull requests merged in 2020-03, with the labels that each got.

#10 Various fixes
  dist/src/modules.js
  dist/src/product-releases.js
  dist/src/target.js
  dist/src/utils.js
  package-lock.json
  package.json
Labels: bug

#11 [FIX] small typo
  README.md
Labels: bug

#13 Fix for the Issue #12
  dist/src/missing-features.js
  package-lock.json
  package.json
Labels: bug, enhancement

#14 Refactor
  config.json
  dist/index.css
  dist/index.html
  dist/index.js
  dist/release-app-data/no-features.js
  dist/release-app-data/only-modules.js
  dist/src/missing-features.js
  dist/src/no-features.js
  dist/src/product-releases.js
  dist/src/target.js
  jarvis.js
  package.json
  server/api-call.js
  server/file-system.js
  server/reset.js
  server/utils.js
Labels: enhancement
